name: Draw.io PR Diagram Changes
on:
  pull_request:
    paths:
      - "**.drawio"

permissions:
  contents: write
  pull-requests: write

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: pr-version

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: base-version

      - name: Prepare git repository for images
        run: |
          # Create and move to a new directory for the image repository
          mkdir image-repository
          cd image-repository
          
          # Initialize git
          git init
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Set up remote
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          
          # Try to fetch existing branch
          git fetch origin pr-${{ github.event.pull_request.number }}-diagrams || true
          
          # Create or switch to the branch
          if git fetch origin pr-${{ github.event.pull_request.number }}-diagrams; then
            git checkout pr-${{ github.event.pull_request.number }}-diagrams
            echo "Branch exists, updating..."
          else
            git checkout --orphan pr-${{ github.event.pull_request.number }}-diagrams
            echo "Creating new branch..."
          fi
          
          # Create directory for the images
          mkdir -p pr-${{ github.event.pull_request.number }}-images
          
          # Copy the exported images
          for file in $(find ../pr-version -name "*.drawio"); do
            filename=$(basename "$file")
            base_name="${filename%.*}"
            
            cp "../base-version/diagrams/exported-diagrams/${base_name}-Page-1.png" "pr-${{ github.event.pull_request.number }}-images/${base_name}-before.png" || true
            cp "../pr-version/diagrams/exported-diagrams/${base_name}-Page-1.png" "pr-${{ github.event.pull_request.number }}-images/${base_name}-after.png" || true
          done
          
          # Stage and commit changes
          git add .
          git commit -m "Update diagram comparison images for PR #${{ github.event.pull_request.number }}" || true
          git push origin pr-${{ github.event.pull_request.number }}-diagrams --force

      - name: Generate comparison comment
        id: generate-comment
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BRANCH: pr-${{ github.event.pull_request.number }}-diagrams
        run: |
          cat > comment.md << 'EOL'
          ### Draw.io Diagram Changes

          EOL
          
          for file in $(find pr-version -name "*.drawio"); do
            filename=$(basename "$file")
            base_name="${filename%.*}"
            
            cat >> comment.md << EOF
          #### ${filename}
          
          **Before:**
          
          <img src="https://raw.githubusercontent.com/$REPO/$BRANCH/pr-$PR_NUMBER-images/${base_name}-before.png" width="500" />
          
          **After:**
          
          <img src="https://raw.githubusercontent.com/$REPO/$BRANCH/pr-$PR_NUMBER-images/${base_name}-after.png" width="500" />
          
          ---
          
          EOF
          done

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: comment.md