name: Draw.io PR Diagram Comparison
on:
  pull_request:
    paths:
      - "**.drawio"

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    steps:
      # First checkout - PR version
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: new-diagrams
          path: pr-version

      # Second checkout - Base version
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: old-diagrams
          path: base-version

      - name: Debug file structure
        run: |
          echo "Current directory structure:"
          ls -R
          echo "PR version diagrams:"
          ls -la pr-version/new-diagrams || echo "Directory not found"
          echo "Base version diagrams:"
          ls -la base-version/old-diagrams || echo "Directory not found"

      - name: Find changed diagrams
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.drawio
          path: pr-version

      - name: Generate comparison comment
        id: generate-comment
        run: |
          comment="### Draw.io Diagram Changes\n\n"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            filename=$(basename "$file")
            base_name="${filename%.*}"
            
            # Add debug information
            echo "Processing file: $filename"
            echo "Base name: $base_name"
            echo "Looking for PR version in: pr-version/new-diagrams/$base_name.png"
            echo "Looking for base version in: base-version/old-diagrams/$base_name.png"
            
            # Check if files exist
            if [ ! -f "base-version/old-diagrams/$base_name.png" ]; then
              echo "Warning: Old version PNG not found"
              ls -la base-version/old-diagrams/
            fi
            if [ ! -f "pr-version/new-diagrams/$base_name.png" ]; then
              echo "Warning: New version PNG not found"
              ls -la pr-version/new-diagrams/
            fi
            
            old_image=$(base64 -w 0 "base-version/old-diagrams/${base_name}-Page-1.png") || echo "Failed to encode old image"
            new_image=$(base64 -w 0 "pr-version/new-diagrams/${base_name}-Page-1.png") || echo "Failed to encode new image"
            
            comment="${comment}#### ${filename}\n\n"
            comment="${comment}**Before:**\n"
            comment="${comment}<img src=\"data:image/png;base64,${old_image}\" width=\"500\">\n\n"
            comment="${comment}**After:**\n"
            comment="${comment}<img src=\"data:image/png;base64,${new_image}\" width=\"500\">\n\n"
            comment="${comment}---\n\n"
          done
          
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$comment" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `${{ steps.generate-comment.outputs.comment }}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: comment
            });