name: Draw.io PR Diagram Comparison
on:
  pull_request:
    paths:
      - "**.drawio"

permissions:
  contents: read
  pull-requests: write

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: diagrams/drawio-assets
          path: pr-version

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: diagrams/drawio-assets
          path: base-version

      - name: Generate comparison comment
        id: generate-comment
        run: |
          {
            echo "### Draw.io Diagram Changes"
            echo
            for file in $(find pr-version -name "*.drawio"); do
              filename=$(basename "$file")
              base_name="${filename%.*}"
              
              OLD_PATH="base-version/diagrams/drawio-assets/${base_name}-Page-1.png"
              NEW_PATH="pr-version/diagrams/drawio-assets/${base_name}-Page-1.png"
              
              echo "#### ${filename}"
              echo
              
              # Debug information
              echo "<details><summary>Debug Info</summary>"
              echo
              echo "Looking for old version at: $OLD_PATH"
              echo "Looking for new version at: $NEW_PATH"
              echo
              if [ -f "$OLD_PATH" ]; then
                echo "✅ Old version found"
                ls -l "$OLD_PATH"
              else
                echo "❌ Old version not found"
                echo "Contents of base-version/diagrams/drawio-assets:"
                ls -la base-version/diagrams/drawio-assets || echo "Directory not found"
              fi
              echo
              if [ -f "$NEW_PATH" ]; then
                echo "✅ New version found"
                ls -l "$NEW_PATH"
              else
                echo "❌ New version not found"
                echo "Contents of pr-version/diagrams/drawio-assets:"
                ls -la pr-version/diagrams/drawio-assets || echo "Directory not found"
              fi
              echo "</details>"
              echo
              
              echo "**Before:**"
              if [ -f "$OLD_PATH" ]; then
                echo
                echo "\`\`\`"
                echo "![Old Version]($OLD_PATH)"
                echo "\`\`\`"
                echo
              else
                echo "❌ Old version not found"
              fi
              echo
              echo "**After:**"
              if [ -f "$NEW_PATH" ]; then
                echo
                echo "\`\`\`"
                echo "![New Version]($NEW_PATH)"
                echo "\`\`\`"
                echo
              else
                echo "❌ New version not found"
              fi
              echo
              echo "---"
              echo
            done
          } > comment.md

          body=$(cat comment.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "comment=$body" >> $GITHUB_OUTPUT

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.generate-comment.outputs.comment }}