name: Draw.io PR Diagram Comparison
on:
  pull_request:
    paths:
      - "**.drawio"

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    steps:
      # First checkout - PR version
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: pr-version/new-diagrams
          path: pr-version

      # Second checkout - Base version
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: base-version/old-diagrams
          path: base-version

      - name: Find changed diagrams
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.drawio
          path: pr-version

      - name: Generate comparison comment
        id: generate-comment
        run: |
          comment="### Draw.io Diagram Changes\n\n"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            filename=$(basename "$file")
            base_name="${filename%.*}"
            
            # Adjust paths to account for the new directory structure
            old_image=$(base64 -w 0 "base-version/old-diagrams/${base_name}.png")
            new_image=$(base64 -w 0 "pr-version/new-diagrams/${base_name}.png")
            
            comment="${comment}#### ${filename}\n\n"
            comment="${comment}**Before:**\n"
            comment="${comment}<img src=\"data:image/png;base64,${old_image}\" width=\"500\">\n\n"
            comment="${comment}**After:**\n"
            comment="${comment}<img src=\"data:image/png;base64,${new_image}\" width=\"500\">\n\n"
            comment="${comment}---\n\n"
          done
          
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$comment" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `${{ steps.generate-comment.outputs.comment }}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: comment
            });
