name: Draw.io PR Diagram Changes
on:
  pull_request:
    paths:
      - "**.drawio"

permissions:
  contents: write
  pull-requests: write

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: pr-version

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: base-version

      # Create a temporary branch to store the images
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create or update images branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Try to fetch the existing branch
          git fetch origin pr-${{ github.event.pull_request.number }}-diagrams || true
          
          # Create or switch to the branch
          if git checkout pr-${{ github.event.pull_request.number }}-diagrams 2>/dev/null; then
            echo "Branch exists, updating..."
          else
            echo "Creating new branch..."
            git checkout -b pr-${{ github.event.pull_request.number }}-diagrams
          fi
          
          # Create directory for the images
          mkdir -p pr-${github.event.pull_request.number}-images
          
          # Copy the exported images with distinct names
          for file in $(find pr-version -name "*.drawio"); do
            filename=$(basename "$file")
            base_name="${filename%.*}"
            
            cp "base-version/diagrams/exported-diagrams/${base_name}-Page-1.png" "pr-${github.event.pull_request.number}-images/${base_name}-before.png" || true
            cp "pr-version/diagrams/exported-diagrams/${base_name}-Page-1.png" "pr-${github.event.pull_request.number}-images/${base_name}-after.png" || true
          done
          
          # Commit and push the images
          git add pr-${github.event.pull_request.number}-images/
          git commit -m "Update diagram comparison images for PR #${{ github.event.pull_request.number }}" || true
          git push origin pr-${{ github.event.pull_request.number }}-diagrams --force

      - name: Generate comparison comment
        id: generate-comment
        env:
          REPO: ${{ github.repository }}
          BRANCH: pr-${{ github.event.pull_request.number }}-diagrams
        run: |
          {
            echo "### Draw.io Diagram Changes"
            echo
            for file in $(find pr-version -name "*.drawio"); do
              filename=$(basename "$file")
              base_name="${filename%.*}"
              
              echo "#### ${filename}"
              echo
              
              echo "**Before:**"
              echo
              echo "<img src=\"https://raw.githubusercontent.com/${REPO}/${BRANCH}/pr-${github.event.pull_request.number}-images/${base_name}-before.png\" width=\"500\" />"
              echo
              echo "**After:**"
              echo
              echo "<img src=\"https://raw.githubusercontent.com/${REPO}/${BRANCH}/pr-${github.event.pull_request.number}-images/${base_name}-after.png\" width=\"500\" />"
              echo
              echo "---"
              echo
            done
          } > comment.md

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: comment.md