name: Draw.io PR Diagram Comparison
on:
  pull_request:
    paths:
      - "**.drawio"

permissions:
  contents: read
  pull-requests: write

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    steps:
      # First checkout - PR version
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: diagrams/new-diagrams
          path: pr-version

      # Second checkout - Base version
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: diagrams/old-diagrams
          path: base-version

      - name: Debug File Structure
        run: |
          echo "Listing all directories:"
          ls -R
          echo "Looking for PNG files:"
          find . -name "*.png"

      - name: Find changed diagrams
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.drawio
          path: pr-version

      - name: Generate comparison comment
        id: generate-comment
        run: |
          {
            echo "### Draw.io Diagram Changes"
            echo
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              filename=$(basename "$file")
              base_name="${filename%.*}"
              
              echo "Processing file: $filename" >&2
              echo "Base name: $base_name" >&2
              
              # Look for PNG files with similar names
              echo "Looking for PNG files matching $base_name:" >&2
              find . -name "*${base_name}*.png" >&2
              
              # Try both with and without Page-1 suffix
              OLD_PATH_1="base-version/diagrams/drawio-assets/${base_name}-Page-1.png"
              OLD_PATH_2="base-version/diagrams/drawio-assets/${base_name}.png"
              NEW_PATH_1="pr-version/diagrams/drawio-assets/${base_name}-Page-1.png"
              NEW_PATH_2="pr-version/diagrams/drawio-assets/${base_name}.png"
              
              echo "Checking paths:" >&2
              echo "OLD_PATH_1: $OLD_PATH_1" >&2
              echo "OLD_PATH_2: $OLD_PATH_2" >&2
              echo "NEW_PATH_1: $NEW_PATH_1" >&2
              echo "NEW_PATH_2: $NEW_PATH_2" >&2
              
              echo "#### ${filename}"
              echo
              echo "**Before:**"
              if [ -f "$OLD_PATH_1" ]; then
                echo "<img src=\"data:image/png;base64,$(base64 -w 0 "$OLD_PATH_1")\" width=\"500\">"
              elif [ -f "$OLD_PATH_2" ]; then
                echo "<img src=\"data:image/png;base64,$(base64 -w 0 "$OLD_PATH_2")\" width=\"500\">"
              else
                echo "Image not found in paths:"
                echo "- $OLD_PATH_1"
                echo "- $OLD_PATH_2"
              fi
              echo
              echo "**After:**"
              if [ -f "$NEW_PATH_1" ]; then
                echo "<img src=\"data:image/png;base64,$(base64 -w 0 "$NEW_PATH_1")\" width=\"500\">"
              elif [ -f "$NEW_PATH_2" ]; then
                echo "<img src=\"data:image/png;base64,$(base64 -w 0 "$NEW_PATH_2")\" width=\"500\">"
              else
                echo "Image not found in paths:"
                echo "- $NEW_PATH_1"
                echo "- $NEW_PATH_2"
              fi
              echo
              echo "---"
              echo
            done
          } > comment.md
          
          echo 'COMMENT<<EOF' >> $GITHUB_ENV
          cat comment.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ env.COMMENT }}