name: Draw.io PR Diagram Changes
on:
  pull_request:
    paths:
      - "**.drawio"

permissions:
  contents: write
  pull-requests: write

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    env:
      STORAGE_BRANCH: diagram-storage # single branch for all PR images
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: pr-version

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: base-version

      - name: Setup storage branch
        run: |
          # Setup git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Create and switch to storage branch
          if git fetch origin $STORAGE_BRANCH; then
            git checkout $STORAGE_BRANCH
          else
            git checkout --orphan $STORAGE_BRANCH
            git rm -rf .
            git commit --allow-empty -m "Initialize diagram storage branch"
          fi
          
          # Create PR-specific directory
          mkdir -p pr-${{ github.event.pull_request.number }}
          
          # Copy the exported images
          for file in $(find pr-version -name "*.drawio"); do
            filename=$(basename "$file")
            base_name="${filename%.*}"
            
            cp "base-version/diagrams/exported-diagrams/${base_name}-Page-1.png" "pr-${{ github.event.pull_request.number }}/${base_name}-before.png" || true
            cp "pr-version/diagrams/exported-diagrams/${base_name}-Page-1.png" "pr-${{ github.event.pull_request.number }}/${base_name}-after.png" || true
          done
          
          # Commit and push changes
          git add .
          git commit -m "Update diagram comparisons for PR #${{ github.event.pull_request.number }}" || true
          git push origin $STORAGE_BRANCH

      - name: Generate comparison comment
        id: generate-comment
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          cat > comment.md << 'EOL'
          ### Draw.io Diagram Changes

          EOL
          
          for file in $(find pr-version -name "*.drawio"); do
            filename=$(basename "$file")
            base_name="${filename%.*}"
            
            cat >> comment.md << EOF
          #### ${filename}
          
          **Before:**
          
          <img src="https://raw.githubusercontent.com/$REPO/$STORAGE_BRANCH/pr-$PR_NUMBER/${base_name}-before.png" width="500" />
          
          **After:**
          
          <img src="https://raw.githubusercontent.com/$REPO/$STORAGE_BRANCH/pr-$PR_NUMBER/${base_name}-after.png" width="500" />
          
          ---
          
          EOF
          done

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: comment.md