name: Draw.io PR Diagram Comparison
on:
  pull_request:
    paths:
      - "**.drawio"

permissions:
  contents: read
  pull-requests: write

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: diagrams/drawio-assets
          path: pr-version

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: diagrams/drawio-assets
          path: base-version

      - name: Generate comparison comment
        id: generate-comment
        env:
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          REPO: ${{ github.repository }}
        run: |
          {
            echo "### Draw.io Diagram Changes"
            echo
            for file in $(find pr-version -name "*.drawio"); do
              filename=$(basename "$file")
              base_name="${filename%.*}"
              rel_path="diagrams/drawio-assets/${base_name}-Page-1.png"
              
              echo "#### ${filename}"
              echo
              
              echo "**Before:**"
              echo
              echo "<img src=\"https://raw.githubusercontent.com/${REPO}/${PR_BASE_SHA}/${rel_path}\" width=\"500\" />"
              echo
              echo "**After:**"
              echo
              echo "<img src=\"https://raw.githubusercontent.com/${REPO}/${PR_HEAD_SHA}/${rel_path}\" width=\"500\" />"
              echo
              echo "---"
              echo
            done
          } > comment.md

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: comment.md