name: Draw.io PR Diagram Changes
on:
  pull_request:
    paths:
      - "**.drawio"

permissions:
  contents: read
  pull-requests: write

jobs:
  compare-diagrams:
    runs-on: ubuntu-latest
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-version

      - name: Export new diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: pr-version

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base-version

      - name: Export old diagram version
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: true
          output: exported-diagrams
          path: base-version

      - name: Debug file structure
        run: |
          echo "=== PR Version Directory Structure ==="
          ls -R pr-version
          echo
          echo "=== Base Version Directory Structure ==="
          ls -R base-version
          echo
          echo "=== Draw.io Files Found ==="
          find . -name "*.drawio"
          echo
          echo "=== Exported PNG Files Found ==="
          find . -name "*.png"

      - name: Generate comparison comment
        id: generate-comment
        run: |
          {
            echo "### Draw.io Diagram Changes"
            echo
            echo "<details><summary>📁 Debug Information</summary>"
            echo
            echo "\`\`\`"
            echo "=== PR Version Files ==="
            ls -R pr-version || echo "No files found in pr-version"
            echo
            echo "=== Base Version Files ==="
            ls -R base-version || echo "No files found in base-version"
            echo
            echo "=== Draw.io Files Found ==="
            find . -name "*.drawio" || echo "No .drawio files found"
            echo
            echo "=== Exported PNG Files ==="
            find . -name "*.png" || echo "No PNG files found"
            echo "\`\`\`"
            echo "</details>"
            echo

            for file in $(find pr-version -name "*.drawio"); do
              filename=$(basename "$file")
              base_name="${filename%.*}"
              
              # Get relative path from the drawio file to construct correct export path
              rel_path=$(dirname "${file#pr-version/}")
              
              OLD_PATH="base-version/exported-diagrams/${rel_path}/${base_name}-Page-1.png"
              NEW_PATH="pr-version/exported-diagrams/${rel_path}/${base_name}-Page-1.png"
              
              echo "#### ${filename}"
              echo
              echo "<details><summary>🔍 File Paths</summary>"
              echo
              echo "Looking for old version at: \`$OLD_PATH\`"
              echo "Looking for new version at: \`$NEW_PATH\`"
              echo "</details>"
              echo
              
              echo "**Before:**"
              echo
              if [ -f "$OLD_PATH" ]; then
                OLD_IMG=$(base64 -w 0 "$OLD_PATH")
                echo "<img src=\"data:image/png;base64,${OLD_IMG}\" width=\"500\" />"
              else
                echo "❌ Old version not found at: $OLD_PATH"
              fi
              echo
              echo "**After:**"
              echo
              if [ -f "$NEW_PATH" ]; then
                NEW_IMG=$(base64 -w 0 "$NEW_PATH")
                echo "<img src=\"data:image/png;base64,${NEW_IMG}\" width=\"500\" />"
              else
                echo "❌ New version not found at: $NEW_PATH"
              fi
              echo
              echo "---"
              echo
            done
          } > comment.md

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: comment.md